Repository alloon-project/photi-ios, pull requests merged in 2024-12, with the labels that each got.

#165 [FEAT]: 비밀번호 찾기 API 구현
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/Vector@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/Vector@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/Vector@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/background.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/background@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/pinking_gray.imageset/background@3x.png
  Projects/DesignSystem/Sources/Card/ProofChallenge/ProofChallengeCellModel.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/FindPasswordContainer.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/FindPasswordCoordinator.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/FindPasswordViewController.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/FindPasswordViewModel.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/TempPassword/TempPasswordContainer.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/TempPassword/TempPasswordCoordinator.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/TempPassword/TempPasswordViewController.swift
  Projects/Presentation/LogIn/Implementations/FindPassword/TempPassword/TempPasswordViewModel.swift
  Projects/Presentation/LogIn/Implementations/LogInContainer.swift
Labels: feature, style

#168 [REFACT] 신고하기 & 문의하기 개선
  Projects/Presentation/MyPage/Implementations/Setting/SettingCoordinator.swift
  Projects/Presentation/Report/Implementations/ReportContainer.swift
  Projects/Presentation/Report/Implementations/ReportCoordinator.swift
  Projects/Presentation/Report/Implementations/ReportViewController.swift
  Projects/Presentation/Report/Interfaces/Report.swift
  Projects/Presentation/Report/Interfaces/ReportType.swift
Labels: refactoring

#172 [FEAT]: Photi Segmented Control 구현
  Projects/Core/Extensions/UIStackView+Extension.swift
  Projects/DesignSystem/Sources/SemgnetControl/PhotiSegmentControl.swift
  Projects/DesignSystem/Sources/SemgnetControl/SegmentButton.swift
Labels: feature

#178 [FEAT]: 챌린지 개별 조회(회원) Feed 화면 UI 구현
  Projects/Core/Extensions/Double+Extension.swift
  Projects/Core/Extensions/UICollectionView+Extension.swift
  Projects/Core/Utils/SelfSizingCollectionView/SelfVerticalSizingCollectionView.swift
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/shutter.white.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/ETC/shutter.white.imageset/default.svg
  Projects/DesignSystem/Sources/Button/TextButton/IconTextButton.swift
  Projects/DesignSystem/Sources/Chip/IconChip/IconChip.swift
  Projects/DesignSystem/Sources/HashTagView/HashTagCell.swift
  Projects/DesignSystem/Sources/HashTagView/HashTagCollectionView.swift
  Projects/DesignSystem/Sources/Navigations/Primary/PhotiNavigationBar.swift
  Projects/DesignSystem/Sources/Popup/ToastView/TagView.swift
  Projects/DesignSystem/Sources/ProgressBar/MediumProgressBar.swift
  Projects/DesignSystem/Sources/ProgressBar/ProgressValueType.swift
  Projects/DesignSystem/Sources/SemgnetControl/PhotiSegmentControl.swift
  Projects/DesignSystem/Sources/SemgnetControl/SegmentButton.swift
  Projects/Presentation/Challenge/Implementations/Dummy.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/Views/FeedCell.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/Views/FeedCollectionHeaderView.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/Views/FeedLikeButton.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/Views/FeedPresentationModel.swift
  Projects/Presentation/Challenge/Implementations/PresentationModel/ChallengeTitlePresentationModel.swift
  Projects/Presentation/Challenge/Implementations/Views/ChallengeTitleView.swift
  Projects/Presentation/Challenge/Interfaces/Challenge.swift
  Projects/Presentation/Challenge/Interfaces/Dummy.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/NoneChallengeHomeViewController.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/NoneChallengeHomeViewModel.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/Views/ChallengInformationView/ChallengeInformationView.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/Views/ChallengInformationView/HashTagCell.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/Views/ChallengeImageCell.swift
  Projects/Presentation/Home/Implementations/Views/HomeBottomView/HomeMyChallengeCell.swift
Labels: feature

#170 [FEAT]: 비밀번호 변경 API 구현
  Projects/App/Sources/AppContainer.swift
  Projects/Data/DTO/ChangePassword/ChangePasswordRequestDTO.swift
  Projects/Data/DataMapper/ChangePasswordDataMapper.swift
  Projects/Data/Repository/Implementations/ChangePasswordRepositoryImpl/ChangePasswordAPI.swift
  Projects/Data/Repository/Implementations/ChangePasswordRepositoryImpl/ChangePasswordRepositoryImpl.swift
  Projects/Data/Repository/Implementations/SignUpRepositoryImpl/SignUpRepositoryImpl.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Repository/Interfaces/ChangePasswordRepository.swift
  Projects/Domain/UseCase/Implementations/ChangePasswordUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChangePasswordUseCase.swift
  Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordContainer.swift
  Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordCoordinator.swift
  Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordViewController.swift
  Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/PasswordChange/PasswordChangeContainer.swift
  Projects/Presentation/MyPage/Implementations/PasswordChange/PasswordChangeCoordinator.swift
  Projects/Presentation/MyPage/Implementations/PasswordChange/PasswordChangeViewModel.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditContainer.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditCoordinator.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingContainer.swift
Labels: refactoring, feature, style
