Repository alloon-project/photi-ios, pull requests merged in 2025-07, with the labels that each got.

#305 [Fix]: 변경된 값 수정 (bundle version)
  Projects/App/Info.plist
Labels: infra

#307 [REFACT]: 이미지뷰 contentMode 수정
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift
Labels: refactoring

#309 [REFACT]: QA수정사항 반영
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengePreview/ChallengePreviewViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/Views/FeedCommentTopView.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewController.swift
  Projects/Presentation/LogIn/Implementations/SignUp/EnterId/EnterIdViewController.swift
  Projects/Presentation/LogIn/Implementations/SignUp/EnterPassword/EnterPasswordViewController.swift
Labels: refactoring, style

#314 [BUG]: 챌린지 타이틀 잘림 현상 수정
  Projects/Presentation/MyPage/Implementations/Views/FeedHistory/FeedHistoryCell.swift
Labels: bug

#321 [BUG]: PROD일때, 빌드 안되는 버그 해결
  Projects/Data/DTO/LogIn/LogInRequestDTO.swift
  Projects/Data/DTO/SignUp/Register/RegisterRequestDTO.swift
  Projects/Data/DTO/SignUp/RequestVerficationCode/RequestVerificationCodeReqeustDTO.swift
  Projects/Data/DTO/SignUp/VerifyCode/VerifyCodeRequestDTO.swift
Labels: bug

#323 [FEAT]: 비밀번호 변경 안내문구 추가
  Projects/Presentation/LogIn/Implementations/ResetPassword/TempPassword/TempPasswordViewController.swift
  Projects/Presentation/LogIn/Implementations/SignUp/EnterEmail/VerifyEmail/VerifyEmailViewController.swift
Labels: feature, style

#327 [FEAT]: 마이페이지 비밀번호 초기화 시 로직 수정
  Projects/App/Sources/AppContainer.swift
  Projects/Domain/UseCase/Implementations/ProfileEidtUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ProfileEditUseCase.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordViewModel.swift
Labels: feature
