Repository alloon-project/photi-ios, pull requests merged in 2025-03, with the labels that each got.

#214 [FEAT]: FeedComment API 연동
  .githooks/pre-commit
  Projects/App/Sources/AppContainer.swift
  Projects/Core/Utils/ServiceConfiguration.swift
  Projects/Data/DTO/Challenge/FeedComment/FeedCommentsResponseDTO.swift
  Projects/Data/DTO/Challenge/FeedDetail/FeedDetailResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/PhotiNetwork/EndPoint.swift
  Projects/Data/PhotiNetwork/TaskType.swift
  Projects/Data/Repository/Implementations/AuthRepositoryImpl/AuthAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/DesignSystem/Sources/Button/IconButton/IconButton.swift
  Projects/DesignSystem/Sources/Popup/Alert/UIViewController+Alert.swift
  Projects/Domain/Entity/Feed.swift
  Projects/Domain/Entity/FeedComment.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/UseCase/Implementations/FeedUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/FeedUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/Views/FeedCommentCell.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/Views/FeedCommentTopView.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/PresentationModel/AuthorPresentationModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/PresentationModel/FeedCommentPresentationModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/PresentationModel/FeedPresentatoinModelMapper.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/Views/FeedLikeButton.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthViewController.swift
Labels: feature

#215 [FEAT]: Challenge 비공개 및 공개 참여 API 구현 완료
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalContainer.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalCoordinator.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalViewController.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewController.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeViewModel.swift
  Projects/Presentation/Challenge/Interfaces/Challenge.swift
  Projects/Presentation/Challenge/Interfaces/NoneMemberChallenge.swift
Labels: feature

#216 [FEAT]: Home(회원 챌린지)시에 연동 완료
  Projects/Data/DTO/Challenge/MyChallenge/MyChallengesResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/DesignSystem/Sources/Popup/Alert/UIViewController+Alert.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Entity/ChallengeSummary.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/HomeUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
  Projects/Domain/UseCase/Interfaces/HomeUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewModel.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeContainer.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeCoordinator.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeViewController.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeViewModel.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/HomeBottomView.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/HomeMyChallengeCell.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/MyChallengePresentationModel.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/MyChallengeFeedPresentationModel.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ChallengeImageView.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ChallengeTitleView.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ProofChallengeCell.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallengePresentationModel.swift
Labels: feature

#223 [FEAT]: Challenge 멤버 파티원 및 소개 API 연결
  Projects/Data/DTO/Challenge/ChallengeDescription/ChallengeDescriptionResponseDTO.swift
  Projects/Data/DTO/Challenge/ChallengeMember/ChallengeMemberResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/DesignSystem/Sources/TextField/LineTextField/LineTextField.swift
  Projects/Domain/Entity/ChallengeDescription.swift
  Projects/Domain/Entity/ChallengeMember.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalCoordinator.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Description/DescriptionContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/Description/DescriptionCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Description/DescriptionViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Description/DescriptionViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Description/Views/DescriptionView.swift
  Projects/Presentation/Challenge/Implementations/Member/Description/Views/RuleDescriptionView.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/ParticipantContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/ParticipantCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/ParticipantViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/ParticipantViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/Views/ParticipantCell.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/Views/ParticipantPresentationModel.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeCoordinator.swift
Labels: feature

#224 [FEAT]: 챌린지 및 챌린지 피드 삭제 API 연결
  Projects/App/Sources/AppContainer.swift
  Projects/Data/DTO/Challenge/FeedComment/FeedCommentResponseDTO.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/Data/Repository/Implementations/FeedRepositoryImpl/FeedAPI.swift
  Projects/Data/Repository/Implementations/FeedRepositoryImpl/FeedRepositoryImpl.swift
  Projects/DesignSystem/Sources/Button/IconButton/IconButton.swift
  Projects/DesignSystem/Sources/DropDown/DropDownView.swift
  Projects/DesignSystem/Sources/Popup/Alert/AlertViewController.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/Repository/Interfaces/FeedRepository.swift
  Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/FeedUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
  Projects/Domain/UseCase/Interfaces/FeedUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/Views/FeedCommentTopView.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewController.swift
  Projects/Presentation/Challenge/Interfaces/Challenge.swift
Labels: feature

#230 [INFRA]: interface 및 자주 참조되는 모듈 static에서 dynamic으로 변경
  Projects/Core/Project.swift
  Projects/Data/Project.swift
  Projects/Domain/Project.swift
  Projects/Presentation/Project.swift
Labels: infra

#229 [REFACT]: 컨플릭 에러 해결
  Projects/App/Sources/AppContainer.swift
  Projects/App/Sources/AppViewController.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/DataMapper/FeedDataMapper.swift
  Projects/Data/Repository/Implementations/FeedHistoryRepositoryImpl/FeedAPI.swift
  Projects/Data/Repository/Implementations/FeedHistoryRepositoryImpl/FeedHistoryRepositoryImpl.swift
  Projects/Data/Repository/Implementations/FeedRepositoryImpl/FeedAPI.swift
  Projects/Data/Repository/Implementations/FeedRepositoryImpl/FeedRepositoryImpl.swift
  Projects/Domain/Repository/Interfaces/FeedRepository.swift
  Projects/Domain/UseCase/Implementations/FeedHistoryUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/FeedUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/FeedHistoryUseCase.swift
  Projects/Domain/UseCase/Interfaces/FeedUseCase.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryContainer.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewController.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
Labels: bug, refactoring
