Repository alloon-project/photi-ios, pull requests merged in 2025-02, with the labels that each got.

#204 [INFRA]: SwiftLint GitHook을 통한 빌드시간 감소
  .githooks/pre-commit
  Tuist/ProjectDescriptionHelpers/Target+Extensions.swift
  Tuist/ProjectDescriptionHelpers/TargetScript+Extensions.swift
  Tuist/ResourceSynthesizers/Colors.stencil
Labels: infra

#201 [FEAT]: 챌린지 비회원 조회 API 연결
  Projects/App/Sources/AppContainer.swift
  Projects/Data/DTO/Challenge/ChallengeDetail/ChallengeDetailResponseDTO.swift
  Projects/Data/DTO/Challenge/EndedChallenge/EndedChallengeResponseDTO.swift
  Projects/Data/DTO/Challenge/HashTagResponseDTO.swift
  Projects/Data/DTO/Challenge/MemberImageResponseDTO.swift
  Projects/Data/DTO/Challenge/PopularChallenge/PopularChallengeResponseDTO.swift
  Projects/Data/DTO/Challenge/RuleResponseDTO.swift
  Projects/Data/DTO/EndedChallenge/EndedChallengeRequestDTO.swift
  Projects/Data/DTO/EndedChallenge/EndedChallengeResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/DataMapper/EndedChallengeDataMapper.swift
  Projects/Data/PhotiNetwork/SupportFiles/BaseResponse.swift
  Projects/Data/Repository/Implementations/AuthRepositoryImpl/AuthAPI.swift
  Projects/Data/Repository/Implementations/AuthRepositoryImpl/AuthRepositoryImpl.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/Data/Repository/Implementations/EndedChallengeRepositoryImpl/EndedChallengeAPI.swift
  Projects/Data/Repository/Implementations/EndedChallengeRepositoryImpl/EndedChallengeRepositoryImpl.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Entity/Challenge.swift
  Projects/Domain/Entity/ChallengeDetail.swift
  Projects/Domain/Entity/ChallengeSummary.swift
  Projects/Domain/Entity/EndedChallenge.swift
  Projects/Domain/Repository/Interfaces/AuthRepository.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/Repository/Interfaces/EndedChallengeRepository.swift
  Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/EndedChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/HomeUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
  Projects/Domain/UseCase/Interfaces/EndedChallengeUseCase.swift
  Projects/Domain/UseCase/Interfaces/HomeUseCase.swift
  Projects/Presentation/Challenge/Implementations/EnterChallengeGoal/EnterChallengeGoalCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/LogInGuide/LogInGuideContainer.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/LogInGuide/LogInGuideCoordinator.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/LogInGuide/LogInGuideViewController.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/LogInGuide/LogInGuideViewModel.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/NoneMemberChallengeViewModel.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/Views/ChallengeDeadLineView.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/Views/ChallengeGoalView.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/Views/ChallengeRuleView.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/Views/ChallengeThumbnailView.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/Views/ChallengeVerificationTimeView.swift
  Projects/Presentation/Challenge/Implementations/NoneMember/Views/InvitationCodeView/InvitationCodeViewController.swift
  Projects/Presentation/Challenge/Interfaces/NoneMemberChallenge.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/NoneChallengeHomeViewModel.swift
  Projects/Presentation/MyPage/Implementations/EndedChallange/EndedChallangeViewModel.swift
  Projects/Presentation/MyPage/Implementations/Views/EndedChallenge/EndedChallengeCardCellPresentaionModel.swift
Labels: feature

#206 [FEAT]: 탈퇴하기 API 연결
  Projects/App/Sources/AppContainer.swift
  Projects/App/Sources/AppCoordinator.swift
  Projects/App/Sources/AppViewController.swift
  Projects/Data/DTO/Resign/ResignRequestDTO.swift
  Projects/Data/DataMapper/ResignDataMapper.swift
  Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignAPI.swift
  Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignRepositoryImpl.swift
  Projects/Domain/Repository/Interfaces/ResginRepository.swift
  Projects/Domain/UseCase/Implementations/ResignUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ResignUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/Participant/ParticipantViewController.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
  Projects/Presentation/MyPage/Implementations/MyPageViewController.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditContainer.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditCoordinator.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignContainer.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignCoordinator.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthContainer.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthCoordinator.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthViewController.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthViewModel.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignViewController.swift
  Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingCoordinator.swift
  Projects/Presentation/MyPage/Interfaces/MyPage.swift
  Projects/Presentation/Report/Implementations/ReportContainer.swift
  Projects/Presentation/Report/Implementations/ReportViewController.swift
Labels: feature

#208 [REFACT]: 코드 수정사항 반영
  Projects/App/Sources/AppContainer.swift
  Projects/Presentation/Report/Implementations/ReportViewController.swift
Labels: refactoring
