Repository alloon-project/photi-ios, pull requests merged in 2025-06, with the labels that each got.

#270 [REFACT]: 챌린지 organizeMode 일부 적용
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewModel.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameViewModel.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeOrganizeCoordinator.swift
Labels: feature

#272 [FEAT]: 마이페이지 메인 화면 API 연결
  Projects/App/Sources/AppContainer.swift
  Projects/App/Sources/AppCoordinator.swift
  Projects/App/Sources/AppViewController.swift
  Projects/App/Sources/AppViewModel.swift
  Projects/Data/DTO/MyPage/UserChallengeHistoryResponseDTO.swift
  Projects/Data/DTO/MyPage/VerifiedChallengeDatesResponseDTO.swift
  Projects/Data/DataMapper/MyPageDataMapper.swift
  Projects/Data/Repository/Implementations/ChangePasswordRepositoryImpl/ChangePasswordRepositoryImpl.swift
  Projects/Data/Repository/Implementations/InquiryRepositoryImpl/InquiryRepositoryImpl.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageAPI.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageRepositoyImpl.swift
  Projects/Data/Repository/Implementations/ProfileEditRepositoryImpl/ProfileEditRepositoryImpl.swift
  Projects/Data/Repository/Implementations/ReportRepositoryImpl/ReportRepositoryImpl.swift
  Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignRepositoryImpl.swift
  Projects/DesignSystem/Sources/CalendarView/CalendarView.swift
  Projects/DesignSystem/Sources/Popup/Alert/AlertViewController.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Entity/MyPageSummary.swift
  Projects/Domain/Repository/Interfaces/MyPageRepository.swift
  Projects/Domain/UseCase/Implementations/AppUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/MyPageUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/AppUseCase.swift
  Projects/Domain/UseCase/Interfaces/MyPageUseCase.swift
  Projects/Presentation/Home/Implementations/HomeCoordinator.swift
  Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
  Projects/Presentation/MyPage/Implementations/MyPageViewController.swift
  Projects/Presentation/MyPage/Implementations/MyPageViewModel.swift
  Projects/Presentation/MyPage/Implementations/Views/ChallengeCountBox.swift
  Projects/Presentation/MyPage/Interfaces/MyPage.swift
Labels: feature

#273 [FEAT]: 챌린지 수정하기 기능 추가
  Projects/Data/DTO/Challenge/ChallengeDetail/ChallengeDetailResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Domain/Entity/ChallengeDetail.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
Labels: feature

#275 [FEAT]: 인증 피드 기록 API 연결
  Projects/Data/DTO/MyPage/FeedHistoryResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/DataMapper/MyPageDataMapper.swift
  Projects/Data/Repository/Implementations/FeedRepositoryImpl/FeedAPI.swift
  Projects/Data/Repository/Implementations/FeedRepositoryImpl/FeedRepositoryImpl.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageAPI.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageRepositoyImpl.swift
  Projects/Domain/Entity/FeedHistory.swift
  Projects/Domain/Repository/Interfaces/FeedRepository.swift
  Projects/Domain/Repository/Interfaces/MyPageRepository.swift
  Projects/Domain/UseCase/Implementations/FeedUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/MyPageUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/FeedUseCase.swift
  Projects/Domain/UseCase/Interfaces/MyPageUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedCoordinator.swift
  Projects/Presentation/Challenge/Interfaces/Challenge.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryContainer.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryCoodinator.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewController.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
  Projects/Presentation/MyPage/Implementations/PresentationModel/EndedChallengeCardCellPresentaionModel.swift
  Projects/Presentation/MyPage/Implementations/PresentationModel/FeedHistoryCellModel.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedHistory/FeedHistoryCell.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedHistory/FeedImageView.swift
Labels: feature

#277 [FEAT]: 마이 페이지 종료된 챌린지 API 연결
  Projects/App/Sources/AppContainer.swift
  Projects/Data/DTO/MyPage/EndedChallengeResponseDTO.swift
  Projects/Data/DataMapper/ChallengeDataMapper.swift
  Projects/Data/DataMapper/MyPageDataMapper.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageAPI.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageRepositoyImpl.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Entity/PageState.swift
  Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
  Projects/Domain/Repository/Interfaces/MyPageRepository.swift
  Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/EndedChallengeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/FeedUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/MyPageUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/SearchUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
  Projects/Domain/UseCase/Interfaces/EndedChallengeUseCase.swift
  Projects/Domain/UseCase/Interfaces/FeedUseCase.swift
  Projects/Domain/UseCase/Interfaces/MyPageUseCase.swift
  Projects/Domain/UseCase/Interfaces/SearchUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewModel.swift
  Projects/Presentation/MyPage/Implementations/EndedChallange/EndedChallangeContainer.swift
  Projects/Presentation/MyPage/Implementations/EndedChallange/EndedChallangeCoordinator.swift
  Projects/Presentation/MyPage/Implementations/EndedChallange/EndedChallangeViewController.swift
  Projects/Presentation/MyPage/Implementations/EndedChallange/EndedChallangeViewModel.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryCoodinator.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewController.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
  Projects/Presentation/MyPage/Implementations/MyPageViewModel.swift
  Projects/Presentation/MyPage/Implementations/PresentationModel/EndedChallengeCardCellPresentaionModel.swift
  Projects/Presentation/MyPage/Implementations/PresentationModel/FeedHistoryCellModel.swift
  Projects/Presentation/MyPage/Implementations/Views/EndedChallenge/EndedChallengeCardCell.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedHistory/FeedHistoryCell.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedHistory/FeedImageView.swift
  Projects/Presentation/SearchChallenge/Implementations/RecentChallenges/RecentChallengesViewModel.swift
  Projects/Presentation/SearchChallenge/Implementations/RecommendedChallenges/RecommendedChallengesViewModel.swift
  Projects/Presentation/SearchChallenge/Implementations/SearchResult/ChallengeTitleResult/ChallengeTitleResultViewModel.swift
  Projects/Presentation/SearchChallenge/Implementations/SearchResult/HashTagResult/HashTagResultViewModel.swift
Labels: feature

#279 [FEAT]: 수정하기 UI 및 데이터 전달 & 화면이동 로직 구현
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengePreview/ChallengePreviewViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeContainer.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyContainer.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewController.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewModel.swift
  Projects/Presentation/Challenge/Implementations/PresentationModel/ChallengeModifyPresentaionModel.swift
  Projects/Presentation/Challenge/Implementations/PresentationModel/ChallengePreviewPresentationModel.swift
Labels: feature

#282 [FEAT]: 마이 페이지 날짜별 피드 조회 UI 구현
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateContainer.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateCoordinator.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateViewController.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
  Projects/Presentation/MyPage/Implementations/MyPageViewController.swift
  Projects/Presentation/MyPage/Implementations/MyPageViewModel.swift
  Projects/Presentation/MyPage/Implementations/PresentationModel/FeedsByDatePresentationModel.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedsByDate/FeedsByDateCell.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedsByDate/FeedsByDateImageView.swift
  Projects/Presentation/MyPage/Implementations/Views/FeedsByDate/FeedsByDateTitleView.swift
Labels: feature

#283 [FEAT]: 챌린지 날짜별 조회 API 연결
  Projects/Data/DTO/MyPage/FeedByDateResponseDTO.swift
  Projects/Data/DataMapper/MyPageDataMapper.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageAPI.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageRepositoyImpl.swift
  Projects/DesignSystem/Sources/CalendarView/Calendar/CalendarCell.swift
  Projects/Domain/Entity/FeedSummary.swift
  Projects/Domain/Repository/Interfaces/FeedHistoryRepository.swift
  Projects/Domain/Repository/Interfaces/MyPageRepository.swift
  Projects/Domain/UseCase/Implementations/MyPageUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/MyPageUseCase.swift
  Projects/Presentation/Challenge/Implementations/Member/Feed/FeedCoordinator.swift
  Projects/Presentation/MyPage/Implementations/FeedHistory/FeedHistoryViewModel.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateContainer.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateCoordinator.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateViewController.swift
  Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateViewModel.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
Labels: feature

#292 [FEAT]: 회원 탈퇴 및 로그아웃 API 연결
  Projects/App/Sources/AppContainer.swift
  Projects/App/Sources/AppCoordinator.swift
  Projects/App/Sources/AppViewController.swift
  Projects/Core/Extensions/String+Extension.swift
  Projects/Data/DTO/Resign/ResignRequestDTO.swift
  Projects/Data/DataMapper/ResignDataMapper.swift
  Projects/Data/Repository/Implementations/LogInRepositoryImpl/LogInRepositoryImpl.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageAPI.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageRepositoyImpl.swift
  Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignAPI.swift
  Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignRepositoryImpl.swift
  Projects/Domain/Repository/Interfaces/LogInRepository.swift
  Projects/Domain/Repository/Interfaces/MyPageRepository.swift
  Projects/Domain/Repository/Interfaces/ResginRepository.swift
  Projects/Domain/UseCase/Implementations/LogInUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/MyPageUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/ProfileEidtUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/ResignUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/SignUpUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/MyPageUseCase.swift
  Projects/Domain/UseCase/Interfaces/ProfileEditUseCase.swift
  Projects/Domain/UseCase/Interfaces/ResignUseCase.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ProfileEditContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ProfileEditCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ProfileEditViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ProfileEditViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Resign/ResignContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Resign/ResignCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Resign/ResignPassword/ResignAuthContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Resign/ResignPassword/ResignAuthCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Resign/ResignPassword/ResignAuthViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Resign/ResignPassword/ResignAuthViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawAuth/WithdrawAuthContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawAuth/WithdrawAuthCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawAuth/WithdrawAuthViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawAuth/WithdrawAuthViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingViewModel.swift
  Projects/Presentation/MyPage/Interfaces/MyPage.swift
Labels: feature

#293 [FEAT]: 챌린지 수정하기 UI & API 구현 완료
  Projects/Core/Utils/ServiceConfiguration.swift
  Projects/Data/DTO/Challenge/ChallengeOrganize/Modify/ChallengeModifyRequestDTO.swift
  Projects/Data/DTO/Challenge/ChallengeOrganize/Organize/ChallengeOrganizeRequestDTO.swift
  Projects/Data/DTO/Challenge/ChallengeOrganize/Organize/ChallengeOrganizeResponseDTO.swift
  Projects/Data/DataMapper/ChallengeOrganizeDataMapper.swift
  Projects/Data/Repository/Implementations/ChallengeOrganizeRepositoryImpl/ChallengeOrganizeAPI.swift
  Projects/Data/Repository/Implementations/ChallengeOrganizeRepositoryImpl/ChallengeOrganizeRepositoryImpl.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Repository/Interfaces/ChallengeOrganizeRepository.swift
  Projects/Domain/Repository/Interfaces/Payload/ChallengeModifyPayload.swift
  Projects/Domain/Repository/Interfaces/Payload/ChallengeOrganizePayload.swift
  Projects/Domain/Repository/Interfaces/Payload/PayloadType.swift
  Projects/Domain/UseCase/Implementations/LogInUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/OrganizeUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/SignUpUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/OrganizeUseCase.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeCover/ChallengeCoverContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeCover/ChallengeCoverViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeCover/ChallengeCoverViewModel.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalCoordinator.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewModel.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeHashtag/ChallengeHashtagContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeHashtag/ChallengeHashtagViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeHashtag/ChallengeHashtagViewModel.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameCoordinator.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameViewModel.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeOrganizeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeRule/ChallengeRuleContainer.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeRule/ChallengeRuleCoordinator.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeRule/ChallengeRuleViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeRule/ChallengeRuleViewModel.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewController.swift
  Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyContainer.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyCoordinator.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewController.swift
  Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewModel.swift
Labels: feature

#297 [FEAT]: 마이 페이지 비밀번호 변경 API 연결 완료
  Projects/App/Sources/AppContainer.swift
  Projects/Data/DTO/MyPage/ChangePasswordRequestDTO.swift
  Projects/Data/DataMapper/ChangePasswordDataMapper.swift
  Projects/Data/DataMapper/MyPageDataMapper.swift
  Projects/Data/Repository/Implementations/ChangePasswordRepositoryImpl/ChangePasswordAPI.swift
  Projects/Data/Repository/Implementations/ChangePasswordRepositoryImpl/ChangePasswordRepositoryImpl.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageAPI.swift
  Projects/Data/Repository/Implementations/MyPageRepositoryImpl/MyPageRepositoyImpl.swift
  Projects/Domain/Entity/APIError.swift
  Projects/Domain/Project.swift
  Projects/Domain/Repository/Interfaces/ChangePasswordRepository.swift
  Projects/Domain/Repository/Interfaces/InquiryRepository.swift
  Projects/Domain/Repository/Interfaces/MyPageRepository.swift
  Projects/Domain/Repository/Interfaces/ReportRepository.swift
  Projects/Domain/UseCase/Implementations/ChangePasswordUseCaseImpl.swift
  Projects/Domain/UseCase/Implementations/ProfileEidtUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/ChangePasswordUseCase.swift
  Projects/Domain/UseCase/Interfaces/InquiryUseCase.swift
  Projects/Domain/UseCase/Interfaces/ProfileEditUseCase.swift
  Projects/Domain/UseCase/Interfaces/ReportUseCase.swift
  Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordViewController.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ChangePassword/ChangePasswordViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ProfileEditContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/ProfileEditCoordinator.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawAuth/WithdrawAuthViewModel.swift
  Projects/Presentation/MyPage/Implementations/Setting/ProfileEdit/Withdraw/WithdrawContainer.swift
  Projects/Presentation/MyPage/Implementations/Setting/SettingContainer.swift
Labels: feature

#301 [REFACT]: 홈에서 챌린지 합류 시 이동 플로우 수정
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeContainer.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeViewController.swift
  Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeViewModel.swift
  Projects/Presentation/Home/Implementations/HomeCoordinator.swift
  Projects/Presentation/Home/Implementations/NoneChallengeHome/NoneChallengeHomeCoordinator.swift
Labels: refactoring, style

#299 [REFACT]: 기기 사이즈별 UI 대응
  Projects/App/Sources/AppContainer.swift
  Projects/App/Sources/AppCoordinator.swift
  Projects/Domain/UseCase/Implementations/SearchUseCaseImpl.swift
  Projects/Domain/UseCase/Interfaces/SearchUseCase.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeCover/ChallengeCoverViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeRule/ChallengeRuleViewController.swift
  Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeStart/ChallengeStartViewController.swift
  Projects/Presentation/SearchChallenge/Implementations/SearchChallengeCoordinator.swift
  Projects/Presentation/SearchChallenge/Implementations/SearchChallengeViewController.swift
  Projects/Presentation/SearchChallenge/Implementations/SearchChallengeViewModel.swift
  Projects/Presentation/SearchChallenge/Interfaces/SearchChallenge.swift
Labels: refactoring
